### ISSUE TITLE
Add support for VMWare

### ISSUE THREAD

**Issue by cawilliamson** [nix-community/nixbox#32]
Hey folks!

I know this is quite against the spirit of open source but I think you would reach a wider business audience by supporting VMWare for your images.

**Comment by zimbatm** [comment]
Hi,

I don't have any problem adding support for VMWare for ideological reasons.

What needs to be solved is how to produce the images since it requires a VMWare license and infrastructure to do the build.

I think as a good first step would be for you to add the support if you are willing to do the work. It's not terribly hard and I can guide you through it if you want. It should take half a day or so. Once that's done we can start thinking on how to automate the builds.

**Comment by zimbatm** [comment]
Hi,

I don't have any problem adding support for VMWare for ideological reasons.

What needs to be solved is how to produce the images since it requires a VMWare license and infrastructure to do the build. Since I don't have access to that it's difficult for me to do the work.

I think as a good first step would be for you to add the support if you are willing to do the work. It's not terribly hard and I can guide you through it if you want. It should take half a day or so. Once that's done we can start thinking on how to automate the builds.

**Comment by PierreR** [comment]
@cawilliamson Master supports vmware. I believe this issue can be closed.
